## Calculadora de Cadenas de Markov

In [3]:
import numpy as np 
import pandas as pd

### Utilizaremos el siguiente ejemplo para poder probar el software

<center><img src="IMAGENRESULTANTE.jpg" alt="No hay imagen" /></center>



Paso 1.- Definimos el arreglo inicial y le damos forma.
En este caso es de $5x5$ entonces lo dejaremos de esta siguiente manera ->

In [17]:
a = np.array([0,0.5,0,0,0.5,0.5,0,0.5,0,0,0,0.5,0,0.5,0,0,0,0.5,0,0.5,0.5,0,0,0.5,0])
newarr = a.reshape(5, 5)

Paso 2.- Visualizamos que nos salio correctamente --->

In [3]:
print(newarr)

[[0.  0.5 0.  0.  0.5]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.5 0. ]]


Paso 3.- Se van a definir las condiciones iniciales en 1 , para cada uno de los eventos, por eso lo vemos como valores de pivoteo en zero,one,two.
y para reforzar los cambiamos a la forma 5,1 para que nos queden de manera vertical

In [64]:
def iteraciones(numero):

    #validamos que sea un numero mayor a uno, recuerden que solo acepta enteros dado que se ocupara la variable
    #numero pare realizar iteraciones ---->

    #creamos los valores iniciales
    if(numero>=1):
        zero = np.array([1,0,0,0,0]).reshape(5, 1)
        one = np.array([0,1,0,0,0]).reshape(5, 1)
        two = np.array([0,0,1,0,0]).reshape(5, 1)
        three = np.array([0,0,0,1,0]).reshape(5, 1)
        four = np.array([0,0,0,0,1]).reshape(5, 1)
    #sugerencia: pueden mejorar este codigo añadiendo listas para crear las variables iniciales de forma dinamica


    #iteramos el numero de veces que se quiera realizar iteraciones
    for x in range(numero):

        #realizamos producto punto de cada uno de los estados iniciales por la matriz de transciocion
        zeroo = np.dot(newarr, zero).reshape(1,5) 
        onee = np.dot(newarr,one).reshape(1,5)
        twoo = np.dot(newarr,two).reshape(1,5)
        threee = np.dot(newarr,three).reshape(1,5)
        fourr = np.dot(newarr,four).reshape(1,5)

        #crearemos la nueva matriz de transicion , apilando cada uno de los arreglos anteriores
        nuevoarreglo = np.append(zeroo,onee)
        nuevoarreglo = np.append(nuevoarreglo,twoo)
        nuevoarreglo = np.append(nuevoarreglo,threee)
        nuevoarreglo = np.append(nuevoarreglo,fourr)

        #seleccionamos nuevamente los valores para que continuen las iteraciones
        zero = (nuevoarreglo[:5])  
        one = (nuevoarreglo[5:10])  
        two = (nuevoarreglo[10:15])  
        three = (nuevoarreglo[15:20]) 
        four = (nuevoarreglo[20:25]) 

    #para terminar construimos nuevamente la matriz final
    arreglo = np.append(zero,one)
    arreglo = np.append(arreglo,two)
    arreglo = np.append(arreglo,three)
    arreglo = np.append(arreglo,four)

    #la mostramos en pantalla con su respectiva forma 5x5
    print(arreglo.reshape(5,5))


In [65]:
#Basta con escribir el nombre de la funcion para mandarla a llamar
iteraciones(5)

[[0.0625  0.3125  0.15625 0.15625 0.3125 ]
 [0.3125  0.0625  0.3125  0.15625 0.15625]
 [0.15625 0.3125  0.0625  0.3125  0.15625]
 [0.15625 0.15625 0.3125  0.0625  0.3125 ]
 [0.3125  0.15625 0.15625 0.3125  0.0625 ]]


- Example 2.19

<p>University administrators have developed a Markov model to simu- late graduation rates at their school. Students might drop out, repeat a year, or move on to the next year. Students have a 3% chance of repeating the year. First-years and sophomores have a 6% chance of dropping out. For juniors and seniors, the drop-out rate is 4%. The transition matrix for the model is</p>



In [66]:
university = np.array([1,0,0,0,0,0,0.06,0.03,0.91,0,0,0,0.06,0,0.03,0.91,0,0,0.04,0,0,0.03,0.93,0,0.04,0,0,0,0.03,0.93,0,0,0,0,0,1])
newUniversity = university.reshape(6, 6)
newUniversity

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.06, 0.03, 0.91, 0.  , 0.  , 0.  ],
       [0.06, 0.  , 0.03, 0.91, 0.  , 0.  ],
       [0.04, 0.  , 0.  , 0.03, 0.93, 0.  ],
       [0.04, 0.  , 0.  , 0.  , 0.03, 0.93],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  ]])

In [67]:
df2 = pd.DataFrame(newUniversity, columns = ['Drop','Fr','So','Jr','Sr','Grad'], index = ['Drop','Fr','So','Jr','Sr','Grad'])
print(df2)

      Drop    Fr    So    Jr    Sr  Grad
Drop  1.00  0.00  0.00  0.00  0.00  0.00
Fr    0.06  0.03  0.91  0.00  0.00  0.00
So    0.06  0.00  0.03  0.91  0.00  0.00
Jr    0.04  0.00  0.00  0.03  0.93  0.00
Sr    0.04  0.00  0.00  0.00  0.03  0.93
Grad  0.00  0.00  0.00  0.00  0.00  1.00


In [102]:
def iteracionesUniversidad(numero):

    #validamos que sea un numero mayor a uno, recuerden que solo acepta enteros dado que se ocupara la variable
    #numero pare realizar iteraciones ---->

    #creamos los valores iniciales
    
    zero = np.array([1,0,0,0,0,0]).reshape(6, 1)
    one = np.array([0,1,0,0,0,0]).reshape(6, 1)
    two = np.array([0,0,1,0,0,0]).reshape(6, 1)
    three = np.array([0,0,0,1,0,0]).reshape(6, 1)
    four = np.array([0,0,0,0,1,0]).reshape(6, 1)
    five = np.array([0,0,0,0,0,1]).reshape(6, 1)


        #sugerencia: pueden mejorar este codigo añadiendo listas para crear las variables iniciales de forma dinamica

        #iteramos el numero de veces que se quiera realizar iteraciones
        
    for x in range(numero+1):
            
        #realizamos producto punto de cada uno de los estados iniciales por la matriz de transciocion
        zero1 = np.dot(newUniversity, zero).reshape(1,6) 
        one1 = np.dot(newUniversity,one).reshape(1,6)
        two1 = np.dot(newUniversity,two).reshape(1,6)
        three1 = np.dot(newUniversity,three).reshape(1,6)
        four1 = np.dot(newUniversity,four).reshape(1,6)
        five1 = np.dot(newUniversity,five).reshape(1,6)

            
        #crearemos la nueva matriz de transicion , apilando cada uno de los arreglos anteriores
        nuevoarreglo = np.append(zero1,one1)
        nuevoarreglo = np.append(nuevoarreglo,two1)
        nuevoarreglo = np.append(nuevoarreglo,three1)
        nuevoarreglo = np.append(nuevoarreglo,four1)
        nuevoarreglo = np.append(nuevoarreglo,five1)

            #numero de iteracion 

        print("Iteracion numero: ",x)
        

        df = pd.DataFrame(nuevoarreglo.reshape(6,6), columns = ['Drop','Fr','So','Jr','Sr','Grad'], index = ['Drop','Fr','So','Jr','Sr','Grad'])
        df = df.applymap("{0:.4f}".format)
        print(df)
            
            #seleccionamos nuevamente los valores para que continuen las iteraciones
        zero = (nuevoarreglo[:6])  
        one = (nuevoarreglo[6:12])  
        two = (nuevoarreglo[12:18])  
        three = (nuevoarreglo[18:24]) 
        four = (nuevoarreglo[24:30]) 
        five = (nuevoarreglo[30:36])

        #para terminar construimos nuevamente la matriz final
    arreglo = np.append(zero,one)
    arreglo = np.append(arreglo,two)
    arreglo = np.append(arreglo,three)
    arreglo = np.append(arreglo,four)
    arreglo = np.append(arreglo,five)

        #la mostramos en pantalla con su respectiva forma 5x5
    return arreglo.reshape(6,6)


In [103]:
x = iteracionesUniversidad(5)


Iteracion numero:  0
        Drop      Fr      So      Jr      Sr    Grad
Drop  1.0000  0.0600  0.0600  0.0400  0.0400  0.0000
Fr    0.0000  0.0300  0.0000  0.0000  0.0000  0.0000
So    0.0000  0.9100  0.0300  0.0000  0.0000  0.0000
Jr    0.0000  0.0000  0.9100  0.0300  0.0000  0.0000
Sr    0.0000  0.0000  0.0000  0.9300  0.0300  0.0000
Grad  0.0000  0.0000  0.0000  0.0000  0.9300  1.0000
Iteracion numero:  1
        Drop      Fr      So      Jr      Sr    Grad
Drop  1.0000  0.1164  0.0982  0.0784  0.0412  0.0000
Fr    0.0000  0.0009  0.0000  0.0000  0.0000  0.0000
So    0.0000  0.0546  0.0009  0.0000  0.0000  0.0000
Jr    0.0000  0.8281  0.0546  0.0009  0.0000  0.0000
Sr    0.0000  0.0000  0.8463  0.0558  0.0009  0.0000
Grad  0.0000  0.0000  0.0000  0.8649  0.9579  1.0000
Iteracion numero:  2
        Drop      Fr      So      Jr      Sr    Grad
Drop  1.0000  0.1529  0.1343  0.0807  0.0412  0.0000
Fr    0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
So    0.0000  0.0025  0.0000  0.0000