### Cadenas de Markov
#### Adolfo Huerta Ramírez

In [36]:
def dotProduct():
    import numpy as np
    numero_columnas = input("introduce el numero de columnas A: ")
    numero_filas = input("introduce el numero de filas A: ")

    numero_columnas = int(numero_columnas)
    numero_filas = int(numero_filas)

    numeros = []

    for x in range(numero_columnas):
        for y in range(numero_filas):
            numero = input("introduce el numero izq - der: ")
            numeros.append(int(numero))



    numero_columnasB = input("introduce el numero de columnas B: ")
    numero_filasB = input("introduce el numero de filas B: ")

    numero_columnasB = int(numero_columnasB)
    numero_filasB = int(numero_filasB)

    numerosB = []

    for x in range(numero_columnasB):
        for y in range(numero_filasB):
            numeroB = input("introduce el numero izq-der: ")
            numerosB.append(int(numeroB))

    A=np.array(numeros).reshape(numero_filas,numero_columnas)
    B=np.array(numerosB).reshape(numero_filasB,numero_columnasB)
    C = np.dot(A,B)
    print(A)
    print(B)
    return C

In [37]:
productoPunto = dotProduct()
print(productoPunto)

[[1 2]
 [3 4]]
[[1]
 [2]]
[[ 5]
 [11]]
